//
// Created by D Rimron-Soutter on 12/11/2020.
//
#ifndef EVIL_BUILD_H
#define EVIL_BUILD_H

// Autogenerated on Sun Nov 22 12:43:41 GMT 2020
#define EVIL_BUILD       "61"
#define EVIL_VER	       "0.1-pr2
"

#endif //EVIL_BUILD_H
