//
// Created by D Rimron-Soutter on 12/11/2020.
//
#ifndef EVIL_BUILD_H
#define EVIL_BUILD_H

// Autogenerated on Mon Nov 27 17:08:32 GMT 2023
#define EVIL_BUILD       "64"
#define EVIL_VER	       "0.1PR2
"

#endif //EVIL_BUILD_H
