//
// Created by D Rimron-Soutter on 12/11/2020.
//
#ifndef EVIL_BUILD_H
#define EVIL_BUILD_H

// Autogenerated on Fri Nov 20 23:12:43 GMT 2020
#define EVIL_BUILD       "55"
#define EVIL_VER	       "0.1-pr2
"

#endif //EVIL_BUILD_H
